[project]
name = "website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["mkdocs-material[imaging]>=9.7.1"]

[project.scripts]
serve = "mkdocs serve --livereload"
